### ISSUE TITLE
How to create indoorGML and turn it to an image

### ISSUE THREAD

**Issue by Vineeth86** [STEMLab/JInedit#1]
Hi ,
I compiled JInedit and able to run it once . [http://tinypic.com/view.php?pic=29pwyrq&s=9#.VrinAPl96Uk]

I need some help in step 2 d) in the wiki 

> After complete to edit floor level, 2 reference points, height of ground, ceiling, door and path of floor plan image, click OK button to save floor property.Switch floor

What are bottom left and top right corner points in 2D . Is it for the floor ? or walls ?

After I create indooGML how to do I convert it back to image 
Read here politesi.polimi.it/bitstream/10589/103464/3/2015_04_COBAN.pdf
in chapter 4 on indoorGML that its possible to  convert it to an image with  resolution of  metres/pixel

**Comment by STEM-DongukSeo** [comment]
Hi,
2 reference points(left bottom and right upper) correspond to end points of image file.
And these points are criteria for generating actual coordinate of geometric data.


JInedit supports creating IndoorGML data, but not supports converting IndoorGML data to image files.

**Comment by Vineeth86** [comment]
Thank you for clarification 
Suppose the 2nd floor's ground is at height 50m from ground level  and ceiling from the 2nd floor's ground is 10m high , the door is 2m high and the floor occupies 10 X 15 m with 3 rooms  then how should I enter the details 

Level : 2
Bottom Left Point : 0,10 
Top right Point : 15,0 
Ground Height : 50
Ceiling Height : 10
Door Height : 2 
Floor plan : Image that I have of the second floor 

Will JInedit be able to create  navigation IndoorGML data also in future

**Comment by STEM-DongukSeo** [comment]
I think you should adjust some elements:
Bottom Left Point : (0, 10)   →  (0, 0)
Top Right Point : (15, 0)   →   (15, 10)
Ceiling Height : 10 → 60

JInedit currently supports only core module of IndoorGML, but will be added navigation module in the future.
