### ISSUE TITLE
Unable to run the app

### ISSUE THREAD

**Issue by benmomo** [STEMLab/JInedit#2]
Hi,
I imported the project into eclipse. Running it as a Maven Project (clean compile package) I got a JAR. I thought I could launch it buy running 
java -jar JInedit-0.0.1-SNAPSHOT.jar
but I get a message of type that there is no Main class in the Manifest
It seems that I'm missing something ...can you please help me?

**Comment by STEM-DongukSeo** [comment]
Hi,
I adjusted the pom.xml of JInedit project, so I think that you can run the project now.
After pull or download the project, please just run MainFrame class of the project in eclipse or use the command 'maven exec:java'.
If this problem still occurs or you have any other problems, please contact me (donguk.seo@pnu.edu).
Thanks.

**Comment by benmomo** [comment]
Hi,
thank you very much! Now I can run the app from Eclipse.
